jobs:
  build:
    docker:
      - image: cimg/base:2020.04
    steps:
      - checkout
      - run:
          name: Master who dis
          command: echo "Hello main main main main main"

workflows:
  version: 2
  circle-test:
    jobs:
      - build