jobs:
  build:
    docker:
      - image: cimg/base:2020.04
    steps:
      - checkout
      - run:
          name: who dis
          command: echo "Hello master master master master master"

workflows:
  version: 2
  circle-test:
    jobs:
      - build